### ISSUE TITLE
optparse-applicative-0.13.0.0 breaks tasty 

### ISSUE THREAD

**Issue by winterland1989** [feuerbach/tasty#145]
This morning [my project](https://github.com/winterland1989/mysql-haskell)'s test break with:

```
Test/Tasty/Patterns.hs:94:7: error:

    • Variable not in scope: (<>) :: Mod f0 a0 -> Mod f1 a1 -> t0

    • Perhaps you meant one of these:

        ‘>’ (imported from Prelude),

        ‘<$>’ (imported from Options.Applicative),

        ‘*>’ (imported from Options.Applicative)

Test/Tasty/Patterns.hs:95:7: error:

    • Variable not in scope:

        (<>) :: t0 -> Mod f2 a2 -> Mod OptionFields TestPattern

    • Perhaps you meant one of these:

        ‘>’ (imported from Prelude),

        ‘<$>’ (imported from Options.Applicative),

        ‘*>’ (imported from Options.Applicative)
``` 

Then i found a new version of optparse-applicative has been release, and introduced this breaking change, so either add an upper bound or migrate tasty is ok.

**Comment by ezyang** [comment]
Yup, I'm affected by this too.

**Comment by phadej** [comment]
versions from `0.10.0.1` to `0.11.0.3` were affected. Added bounds on Hackage.

**Comment by feuerbach** [comment]
Thanks for the report, should be fixed now.

**Comment by RyanGlScott** [comment]
`tasty-golden` (version 2.3.1, at least) is still broken when built against `optparse-applicative-0.13.0.0`:

```
Building tasty-golden-2.3.1...
Preprocessing library tasty-golden-2.3.1...
[1 of 4] Compiling Test.Tasty.Golden.Internal ( Test/Tasty/Golden/Internal.hs, dist/build/Test/Tasty/Golden/Internal.o )

Test/Tasty/Golden/Internal.hs:38:7: error:
    • Variable not in scope:
        (<>) :: Mod f0 a0 -> Mod f1 a1 -> Mod FlagFields Bool
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
```

**Comment by hvr** [comment]
@feuerbach *bump* this is not fixed yet; all 12 releases since `tasty-golden-2.2.1` on Hackage need attention
![untitled](https://cloud.githubusercontent.com/assets/285533/17959343/0ee298a6-6aa0-11e6-878c-e4b88d20fdde.png)

**Comment by feuerbach** [comment]
Those 12 releases happen to contain a "bug". I have fixed the "bug" by releasing a new version. People should use the latest version to avoid the known bugs. This is how versions work.

(I know what you want me to do, but I don't agree that I *have* to do that. People who have more spare time are free to support the last 12 versions of their packages if they want.)

**Comment by hvr** [comment]
>  People should use the latest version to avoid the known bugs. This is how versions work.

That may be a valid point of view, but the fact is that our infrastructure (PVP, Cabal solver, Hackage, ...) doesn't work that way.

You can disagree with the way Hackage ecosystem works, but if you publish things to Hackage, you're expected to comply with the stated conventions,  as otherwise you shift the cost away from you to everyone else who does comply, thereby multiplying to the total cost significantly. I totally understand, that you value your time, but please think also that other people's time may be equally valuable!

**Comment by feuerbach** [comment]
> That may be a valid point of view, but the fact is that our infrastructure (PVP, Cabal solver, Hackage, ...) doesn't work that way.

Stack and stackage work that way, which is one of the reasons people increasingly use them instead.

> I totally understand, that you value your time, but please consider that other people's time may be equally valuable!

I do consider their time, and my policy is the result of this consideration. If a rare person who:

1. doesn't use stackage, stack, or cabal freeze to get a fixed, reproducible build, and
2. doesn't use cabal to grab the latest version of everything

has to spend some time to untangle their version mess, so be it.

**Comment by Blaisorblade** [comment]
Didn't people invent Hackage revisions and trustees exactly to address @feuerbach's needs?

**Comment by ezyang** [comment]
There is a bit that has been left unsaid in this ticket, so I just want to set out some explicit context:

* 12 releases of tasty have version bounds which incorrectly claim that optparse-applicative-0.13.0.0 builds with them, which it does not

* The requested fix is to edit the Cabal file, using https://hackage.haskell.org/package/tasty/maintain interface, which lets you just go and make a modification to the Cabal file text. It then gets automatically propagated to all users of the package when they update their index. (Pro-tip: when you install a package from Hackage, you're installing the tarball, PLUS a Cabal file overlay from the index.) I guess there's a chance that you will typo and screw up, but it doesn't look like this should take more than a few minutes to update the Cabal files. There are two sets of people who have the ability to edit Cabal files using this interface: trustees, and package authors.

* @feuerbach appears to object, on principle, to having to update Cabal files of old versions of his software, which he doesn't want to support. That's "Someone Else's Problem". (To be clear, I am sympathetic!)

* @hvr would like @feuerbach to pitch in, because otherwise the Hackage Trustees doesn't scale; if the work of keeping bounds up to date can be decentralized, that's less work for Hackage Trustees.

* @hvr has already gone ahead and updated the bounds (according to him, it took five minutes), so this ticket should be closed.

I think there's is something to be said for making Hackage Trustees a wider, more collaborative effort; anyone who uses the dependency solver ought to be able to pitch in when they notice plans stop working. It seems to me that this is the most scalable way in the future.

**Comment by hvr** [comment]
@Blaisorblade indeed, but Trustees rely on the cooperation of package authors (and actually many package authors do!). We can help out when possible here and there, and fix the occasional oversight. But it doesn't scale if we have to do all the edits.

That being said, I edited the 12 affected versions already a couple of days ago as this was causing transitive problems elsewhere (that weren't addressed by the 2.3.1.1 release):

 - http://hackage.haskell.org/package/tasty-golden-2.2.1/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.1.1/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.1.2/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.2/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.2.1/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.2.2/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.2.3/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.2.2.4/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.3/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.3.0.1/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.3.0.2/revisions
 - http://hackage.haskell.org/package/tasty-golden-2.3.1/revisions

**Comment by 23Skidoo** [comment]
> @feuerbach appears to object, on principle, to having to update Cabal files of old versions of his software, which he doesn't want to support. That's "Someone Else's Problem". (To be clear, I am sympathetic!)

In an ideal world, this kind of thing would be fully or partially automated. But we're not there yet.

**Comment by hvr** [comment]
@23Skidoo in an ideal world where semantic versioning was taken seriously, we wouldn't have the need to automate fixing old versions of software in the first place, because that would be rather the exception than the norm, and most likely not be automatable at all. 

We _do_ want to improve the tooling to help with automating the recommended PVP-workflow though, and making it easier to relax bounds (rather than having to add missing upper bounds all over the place which causes unnecessary strain on Hackage & cabal, which are designed and optimised for the dual/diametral PVP-workflow).

This would address @feuerbach concerns (of not wanting to have to care about old versions, and only concentrate on latest versions, and in general keep package maintainance the author has to do reasonably low) as well as make Hackage Trustee's workload reasonable, and overall reduce the conflict.

**Comment by 23Skidoo** [comment]
@hvr 
> (rather than having to add missing upper bounds all over the place which causes unnecessary strain on Hackage & cabal, which are designed and optimised for the dual/diametral PVP-workflow)

You're right that it will increase the number of x-hackage-revision files in the index tarball. I wonder if the package index format can be improved to scale better with respect to the number of post-release updates per package. It's interesting that Git doesn't seem to be the most efficient format: fresh checkout of the all-cabal-files repo requires ~90 MiB bandwidth, while 00-index.tar.gz is only 13 MiB.

**Comment by Blaisorblade** [comment]
> It's interesting that Git doesn't seem to be the most efficient format: fresh checkout of the all-cabal-files repo requires ~90 MiB bandwidth, while 00-index.tar.gz is only 13 MiB.

Did you use `--depth 1` for more comparable results?

**Comment by 23Skidoo** [comment]
@Blaisorblade You're right, I should've compared it with 01-index.tar.gz, which stores the full history of updates and is 47 MiB.

**Comment by phadej** [comment]
@23Skidoo
> I wonder if the package index format can be improved to scale better with respect to the number of post-release updates per package. 

IMHO it's not a problem worth solving. For my own packages which has PVP dictated upper bounds on old dependencies, I don't remember I had to do restricting edits on old packages (except few times where I *did* a mistake in the first place). However I did some relaxing edits. It's difficult to quality which is cheaper in terms of edits, as it depends on release velocity of packages in the dependency graph.

The PVP dictated workflow doesn't rely on ability to make metadata revisions. In current Hackage architecture they are considered exceptional (except maybe for relaxing bounds for the latest release: even that doesn't have an effect on the index size, it makes Hackage as a whole smaller). IIRC `stack`/*Stackage* people don't really like revisions, and I don't like either. The only solution is to adhere to semantic versioning scheme Hackage asks you to: PVP.

I have also been hit by not following PVP, which says that you should have upper bound up to minor part, if you define orphans. I didn't, it was a mistake, I learned it hard-way: http://hackage.haskell.org/package/aeson-extra-0.3.0.0/revisions/ However currently I'm very sure that e.g. `binary-orphans` won't break while I'm on vacation, even it does risky business as defining orphans is.

Also saying that "use latest version" isn't always possible. Some dependency (say `tasty-myhelpers`) might not be yet compatible with the latest release. But I want to update `optparse-applicate` elsewhere. I cannot, even solver (and `stack`) permits me to try the build. As a user of Hackage, I expect that if I find an acceptable install plan *for any version of the package*, it will also build. Otherwise it's a bug.

If not-latest-versions aren't supported, and author don't care about them. Then add `base<0` constraint. It's a very strong way to say "don't even try to build this, ever". This of course will break all Stackage snapshots including old versions. Solution: specify semantic upper bounds, to allow current (at the time) versions of dependencies. The `optparse-applicative` "relaxing bump" required actual code changes.

I don't bet that `optparse-applicative-0.14` would break `tasty` (as it seems that change forcing it is quite small atm: https://github.com/pcapriotti/optparse-applicative/pull/223), but cannot be so sure about `optparse-applicative-0.15`. No author of any package should ever feel bad about making a new major release, breaking changes are sometimes inevitable, there are rules (semantic versioning!) to notify people about them, and give them their time to adapt.

Following is probably suited for another thread somewhere else: I don't really understand why not to have semantic upper bounds. Yes there are packages with large surface API, like `lens`, so it's might be annoying to bump the bounds, as even small part in `lens` change, the whole API is versioned. Same with e.g. `aeson`, if you only use `encode` and `decode`, and not even define your own instances, it's *quite safe* to assume they will be there even major bump occurs. I personally use `aeson` thru `aeson-compat` (if it's enough), which gives much smaller API surface, restricted view if you want. Which have been the same thru two major bumps already (and supports much older ones as well). But the packages like `optparse-applicative` or `haskell-src-exts`: if they change, they usually change hard. In major cases everything breaks. I don't see any excuse to not have upper bounds on them.
